### ISSUE TITLE
怎么卸载docker跟Docker Compose

### ISSUE THREAD

**Issue by sd46235599111** [SuperManito/LinuxMirrors#10]
## 1. 处理器架构

- [ x] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] `Debian`
- [x ] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS`
- [ ] `Fedora`

## 3. 使用环境版本

A：

### (1) 具体问题
A：
怎么卸载docker跟Docker Compose ？
我自己家的旧主板装了个ubuntu18.04系统，安装了你这边提供的docker跟Docker Compose，
https://supermanito.github.io/Helloworld/#/install/安装容器服务，这里的代码安装，发现不好用，怎么卸载呢？我不想旧电脑重装Ubuntu比较麻烦，所以问问，有没有卸载命令？

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
- Docker
```bash
apt-get remove -y docker* 或 yum remove -y docker*
```

- Docker Compose
```bash
rm -rf /usr/local/bin/docker-compose
```

**Comment by SuperManito** [comment]
脚本只是脚本，脚本内的代码通过官方渠道安装 Docker ，而且实在无法理解你问题的逻辑，不好用指的是什么？跟重装系统又有什么关系？

**Comment by sd46235599111** [comment]
> 脚本只是脚本，脚本内的代码通过官方渠道安装 Docker ，而且实在无法理解你问题的逻辑，不好用指的是什么？跟重装系统又有什么关系？

![image](https://user-images.githubusercontent.com/77275992/149652587-36b9c33d-e14d-4d81-ad55-b0afff1a85da.png)

![image](https://user-images.githubusercontent.com/77275992/149652647-f50ab322-d25d-4403-8431-12e6fe846201.png)

复制过来编排错乱了

**Comment by sd46235599111** [comment]
![image](https://user-images.githubusercontent.com/77275992/149652819-bba36860-e888-4c13-9546-5a25eb1bf17f.png)

![image](https://user-images.githubusercontent.com/77275992/149652844-e66547cd-e6cd-488c-b1a1-ce13a7370df6.png)

手动编排改好，甚至使用以前的我自己弄的正确模板docker-compose.yaml ，启动没问题的，也是报这个错

**Comment by SuperManito** [comment]
> ![image](https://user-images.githubusercontent.com/77275992/149652819-bba36860-e888-4c13-9546-5a25eb1bf17f.png)
> 
> ![image](https://user-images.githubusercontent.com/77275992/149652844-e66547cd-e6cd-488c-b1a1-ce13a7370df6.png)
> 
> 手动编排改好，甚至使用以前的我自己弄的正确模板docker-compose.yaml ，启动没问题的，也是报这个错

每个 `-` 前再缩进2个空格

**Comment by SuperManito** [comment]
缩进问题排版的时候没发现，复制是你自己的问题，这跟docker安装脚本没有什么关系

**Comment by sd46235599111** [comment]
> 缩进问题排版的时候没发现，复制是你自己的问题，这跟docker安装脚本没有什么关系

![image](https://user-images.githubusercontent.com/77275992/149653225-fec380c8-ada3-469d-8729-f31f4fc44f35.png)

**Comment by SuperManito** [comment]
> > 缩进问题排版的时候没发现，复制是你自己的问题，这跟docker安装脚本没有什么关系
> 
> ![image](https://user-images.githubusercontent.com/77275992/149653225-fec380c8-ada3-469d-8729-f31f4fc44f35.png)

```yaml
version: "2.0"
services:
jd:
  image: supermanito/helloworld:latest  # 镜像名，可以使用阿里云仓库的备用镜像
  container_name: jd  # 容器名（可随意更改）
  hostname: jd  # 主机名（可随意更改）
  restart: always  # 开机自启
  tty: true  # 开启终端
  network_mode: bridge  # 容器网络类型，如果是旁路由可能需要切换为 host 类型
  ports:
    - 5678:5678  # 端口映射，格式为 "主机端口:容器端口"，主机端口号可自定义，容器端口用来访问控制面板不可修改
  volumes:
    - /opt/jd/config:/jd/config       # 定义配置文件的主机挂载目录为 /opt/jd/config
    - /opt/jd/log:/jd/log             # 定义日志文件的主机挂载目录为 /opt/jd/log
    - /opt/jd/scripts:/jd/scripts      # 定义 Scripts 仓库脚本的主机挂载目录为 /opt/jd/scripts
    - /opt/jd/own:/jd/own             # 定义 Own 仓库脚本的主机挂载目录为 /opt/jd/own
  #  - /opt/jd/jbot:/jd/jbot        # 定义 Telegram Bot 的主机挂载目录为 /opt/jd/jbot
  environment:
    - ENABLE_SCRIPTS_PROXY=true  # 是否为主要脚本仓库启用代理
    - ENABLE_ALL_ENV=true        # 是否在容器启动时预装环境包与常用模块
    - ENABLE_WEB_PANEL=true      # 是否在容器启动时启用控制面板功能
    - ENABLE_HANGUP=false        # 是否在容器启动时启用后台挂机功能
    - ENABLE_TG_BOT=false        # 是否在容器启动时启用 Telegram Bot 功能
```

> 这是正确的格式，官网已经改了
